---
apiVersion: v1
kind: Service
metadata:
  name: favoritessvc
  namespace: cloudmovies
  labels:
    app.kubernetes.io/name: favoritessvc
spec:
  ports:
  - name: favoritessvc
    port: 5003
    targetPort: 5003
  selector:
    app.kubernetes.io/name: favorites
