kind: PersistentVolume
apiVersion: v1
metadata:
  name: userdb-pv
  labels:
    type: userdb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/userdb"
