---
apiVersion: v1
kind: Service
metadata:
  name: userdbsvc
  namespace: cloudmovies
  labels:
    app.kubernetes.io/name: userdbsvc
spec:
  ports:
  - name: userdbport
    port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app.kubernetes.io/name: userdb
