apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: cloudmovies
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 0.1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "init"
