---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moviedb
  namespace: cloudmovies
  labels:
    app.kubernetes.io/name: moviedb
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mysqld
          image: robyt96/cloudmovies_moviedb:1.0
          ports:
            - name: mysqld
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: data-db
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data-db
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 0.5Gi
