---
apiVersion: v1
kind: Service
metadata:
  name: mysqlsvc
  namespace: cloudmovies
  labels:
    app.kubernetes.io/name: mysqlsvc
spec:
  ports:
  - name: mysqld
    port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app.kubernetes.io/name: mysql
