kind: PersistentVolume
apiVersion: v1
metadata:
  name: moviedb-pv
  labels:
    type: moviedb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/moviedb"
