---
apiVersion: v1
kind: Service
metadata:
  name: favoritesdbsvc
  namespace: cloudmovies
  labels:
    app.kubernetes.io/name: favoritesdbsvc
spec:
  ports:
  - name: favoritesdbport
    port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app.kubernetes.io/name: favoritesdb
