kind: PersistentVolume
apiVersion: v1
metadata:
  name: favoritesdb-pv
  labels:
    type: favoritesdb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/favoritesdb"
