---
apiVersion: v1
kind: Service
metadata:
  name: authsvc
  namespace: cloudmovies
  labels:
    app.kubernetes.io/name: authsvc
spec:
  ports:
  - name: authsvc
    port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/name: auth
