---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authdeployment
  namespace: cloudmovies
  labels:
    app.kubernetes.io/name: authdeployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: auth
          image: robyt96/cloudmovies_authapi:1.1
          ports:
            - name: auth
              containerPort: 5000
              protocol: TCP
