---
apiVersion: v1
kind: Service
metadata:
  name: websvc
  namespace: cloudmovies
  labels:
    app.kubernetes.io/name: websvc
spec:
  ports:
  - name: websvc
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: web

